PROJECT_ROOT ?= $(abspath ..)

SOURCE_DIRS := src mul

EXPORT_CONFIG_DIR = test
EXPORT_CONFIG_FILES += abc.conf def.conf calc
EXPORT_FILES_DIR = test
EXPORT_FILES += ddd afile

include $(PROJECT_ROOT)/scripts/library.mk
